### PR TITLE
Recoverable connection pool

### LINKED ISSUE #2065: Fix Query Syntax Error in `redis_store`
The `nativelink-scheduler` is failing due to a RediSearch keyword conflict with the field name "state". This causes index creation errors and stalls the system.

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
# Description
I have replaced the default fred Redis client pool with a custom `RecoverablePool` to address the system stalling issues caused by poor client recovery. `RecoverablePool` is really only a pool that manages a list of `fred::clients::Client instances.`

This is only meant to be a PoC

Fixes #2065 I believe that this issue is multi-faceted and related to connection storms, redis connection pools, and race conditions.

## Type of change

Please delete options that aren't relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/2067)

### CODE REVIEW

File: nativelink-store/src/redis_store.rs [hunk 1]
```diff
@@ -98,11 +98,87 @@ const DEFAULT_SCAN_COUNT: u32 = 10_000;
...
+
+    fn next(&self) -> Client {
+        let clients = self.clients.read();
+        let index = self
+            .counter
+            .fetch_add(1, core::sync::atomic::Ordering::Relaxed);
+        clients[index % clients.len()].clone()
+    }
+
+    async fn replace_client(&self, old_client: &Client) -> Result<Client, Error> {
```
Comment (MarcusSorealheis) [inline nativelink-store/src/redis_store.rs:139]: I need did some testing and I need to do some more thinking here. Here is the problem: Every call to `replace_client` eagerly builds and connects a brand-new Client before it acquires the write lock to see if the old handle is still present. When the target slot has already been replaced by another task ( weethe None branch at lines 157‑165), we now return that freshly-built client even though it never enters the pool. 

Any concurrent reconnect storm therefore spawns one extra TCP connection per racing task, only to drop it again after a single request 😭 . On a busy instance a single node flake can suddenly create dozens of unnecessary Redis connections, exhaust FD limits, and hammer the server with repeated AUTH/HELLO. We should only build a new client once we know we actually need to swap the slot (or fall back to handing out an existing pooled client, as the code previously did).

**Comment by amankrx** [comment]
Tested this out, None of the jobs reached reached the workers, and all of them were stuck in scheduler state and eventually got killed due to an OOM error.

**Comment by MarcusSorealheis** [comment]
@amankrx is that still accurate? I am pretty sure everything is passing on all large workloads. Could you confirm how your tests went?

**Review by amankrx — APPROVED** [review]

**Comment by MarcusSorealheis** [comment]
Cached also @amankrx
